/********************************************************************
* TWaveformdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TWaveformdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTWaveformdict();
extern void G__cpp_setup_inheritanceTWaveformdict();
extern void G__cpp_setup_typetableTWaveformdict();
extern void G__cpp_setup_memvarTWaveformdict();
extern void G__cpp_setup_globalTWaveformdict();
extern void G__cpp_setup_memfuncTWaveformdict();
extern void G__cpp_setup_funcTWaveformdict();
extern void G__set_cpp_environmentTWaveformdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TWaveform.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TWaveformdictLN_TClass;
extern G__linked_taginfo G__TWaveformdictLN_TBuffer;
extern G__linked_taginfo G__TWaveformdictLN_TMemberInspector;
extern G__linked_taginfo G__TWaveformdictLN_TObject;
extern G__linked_taginfo G__TWaveformdictLN_TNamed;
extern G__linked_taginfo G__TWaveformdictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TWaveformdictLN_string;
extern G__linked_taginfo G__TWaveformdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TWaveformdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TWaveformdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TWaveformdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TWaveformdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TWaveformdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TWaveformdictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TWaveformdictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TWaveformdictLN_TH2F;
extern G__linked_taginfo G__TWaveformdictLN_fitParam;
extern G__linked_taginfo G__TWaveformdictLN_TWaveform;
extern G__linked_taginfo G__TWaveformdictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TWaveformdictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TWaveformdictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TWaveformdictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
